//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_40
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// КартДоступ.
    /// </summary>
    // *** Start programmer edit section *** (КартДоступ CustomAttributes)

    // *** End programmer edit section *** (КартДоступ CustomAttributes)
    [AutoAltered()]
    [Caption("Карты Доступа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КартДоступE", new string[] {
            "СправСотр as \'Сотрудник\'",
            "СправСотр.ФИОСотр as \'Ответственный\'"})]
    [AssociatedDetailViewAttribute("КартДоступE", "База_Данных", "База_ДанныхE", true, "", "База Данных", true, new string[] {
            ""})]
    [View("КартДоступL", new string[] {
            "СправСотр.ФИОСотр as \'Ответственный\'"})]
    public class КартДоступ : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Prilozhenie_40.СправСотр fСправСотр;
        
        private IIS.Prilozhenie_40.DetailArrayOfБаза_Данных fБаза_Данных;
        
        // *** Start programmer edit section *** (КартДоступ CustomMembers)

        // *** End programmer edit section *** (КартДоступ CustomMembers)

        
        /// <summary>
        /// КартДоступ.
        /// </summary>
        // *** Start programmer edit section *** (КартДоступ.СправСотр CustomAttributes)

        // *** End programmer edit section *** (КартДоступ.СправСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СправСотр"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_40.СправСотр СправСотр
        {
            get
            {
                // *** Start programmer edit section *** (КартДоступ.СправСотр Get start)

                // *** End programmer edit section *** (КартДоступ.СправСотр Get start)
                IIS.Prilozhenie_40.СправСотр result = this.fСправСотр;
                // *** Start programmer edit section *** (КартДоступ.СправСотр Get end)

                // *** End programmer edit section *** (КартДоступ.СправСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартДоступ.СправСотр Set start)

                // *** End programmer edit section *** (КартДоступ.СправСотр Set start)
                this.fСправСотр = value;
                // *** Start programmer edit section *** (КартДоступ.СправСотр Set end)

                // *** End programmer edit section *** (КартДоступ.СправСотр Set end)
            }
        }
        
        /// <summary>
        /// КартДоступ.
        /// </summary>
        // *** Start programmer edit section *** (КартДоступ.База_Данных CustomAttributes)

        // *** End programmer edit section *** (КартДоступ.База_Данных CustomAttributes)
        public virtual IIS.Prilozhenie_40.DetailArrayOfБаза_Данных База_Данных
        {
            get
            {
                // *** Start programmer edit section *** (КартДоступ.База_Данных Get start)

                // *** End programmer edit section *** (КартДоступ.База_Данных Get start)
                if ((this.fБаза_Данных == null))
                {
                    this.fБаза_Данных = new IIS.Prilozhenie_40.DetailArrayOfБаза_Данных(this);
                }
                IIS.Prilozhenie_40.DetailArrayOfБаза_Данных result = this.fБаза_Данных;
                // *** Start programmer edit section *** (КартДоступ.База_Данных Get end)

                // *** End programmer edit section *** (КартДоступ.База_Данных Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартДоступ.База_Данных Set start)

                // *** End programmer edit section *** (КартДоступ.База_Данных Set start)
                this.fБаза_Данных = value;
                // *** Start programmer edit section *** (КартДоступ.База_Данных Set end)

                // *** End programmer edit section *** (КартДоступ.База_Данных Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КартДоступE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартДоступE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартДоступE", typeof(IIS.Prilozhenie_40.КартДоступ));
                }
            }
            
            /// <summary>
            /// "КартДоступL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартДоступL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартДоступL", typeof(IIS.Prilozhenie_40.КартДоступ));
                }
            }
        }
    }
}
