//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_40
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СправУч.
    /// </summary>
    // *** Start programmer edit section *** (СправУч CustomAttributes)

    // *** End programmer edit section *** (СправУч CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправУчE", new string[] {
            "Фио as \'Фио Ученика\'",
            "СправРодит as \'Родители\'",
            "СправРодит.Фио as \'Фио Родителя\'"})]
    [View("СправУчL", new string[] {
            "Фио as \'Фио Ученика\'"})]
    public class СправУч : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        private IIS.Prilozhenie_40.СправРодит fСправРодит;
        
        // *** Start programmer edit section *** (СправУч CustomMembers)

        // *** End programmer edit section *** (СправУч CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (СправУч.Фио CustomAttributes)

        // *** End programmer edit section *** (СправУч.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (СправУч.Фио Get start)

                // *** End programmer edit section *** (СправУч.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (СправУч.Фио Get end)

                // *** End programmer edit section *** (СправУч.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправУч.Фио Set start)

                // *** End programmer edit section *** (СправУч.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (СправУч.Фио Set end)

                // *** End programmer edit section *** (СправУч.Фио Set end)
            }
        }
        
        /// <summary>
        /// СправУч.
        /// </summary>
        // *** Start programmer edit section *** (СправУч.СправРодит CustomAttributes)

        // *** End programmer edit section *** (СправУч.СправРодит CustomAttributes)
        [PropertyStorage(new string[] {
                "СправРодит"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_40.СправРодит СправРодит
        {
            get
            {
                // *** Start programmer edit section *** (СправУч.СправРодит Get start)

                // *** End programmer edit section *** (СправУч.СправРодит Get start)
                IIS.Prilozhenie_40.СправРодит result = this.fСправРодит;
                // *** Start programmer edit section *** (СправУч.СправРодит Get end)

                // *** End programmer edit section *** (СправУч.СправРодит Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправУч.СправРодит Set start)

                // *** End programmer edit section *** (СправУч.СправРодит Set start)
                this.fСправРодит = value;
                // *** Start programmer edit section *** (СправУч.СправРодит Set end)

                // *** End programmer edit section *** (СправУч.СправРодит Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправУчE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправУчE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправУчE", typeof(IIS.Prilozhenie_40.СправУч));
                }
            }
            
            /// <summary>
            /// "СправУчL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправУчL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправУчL", typeof(IIS.Prilozhenie_40.СправУч));
                }
            }
        }
    }
}
