//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_40
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СправСотр.
    /// </summary>
    // *** Start programmer edit section *** (СправСотр CustomAttributes)

    // *** End programmer edit section *** (СправСотр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправСотрE", new string[] {
            "ФИОСотр as \'Сотрудник\'",
            "СправДолж as \'Должность\'",
            "СправДолж.Должность as \'Должность\'"}, Hidden=new string[] {
            "СправДолж.Должность"})]
    [View("СправСотрL", new string[] {
            "ФИОСотр as \'Сотрудник\'",
            "СправДолж.Должность as \'Должность\'"})]
    public class СправСотр : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИОСотр;
        
        private IIS.Prilozhenie_40.СправДолж fСправДолж;
        
        // *** Start programmer edit section *** (СправСотр CustomMembers)

        // *** End programmer edit section *** (СправСотр CustomMembers)

        
        /// <summary>
        /// ФИОСотр.
        /// </summary>
        // *** Start programmer edit section *** (СправСотр.ФИОСотр CustomAttributes)

        // *** End programmer edit section *** (СправСотр.ФИОСотр CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОСотр
        {
            get
            {
                // *** Start programmer edit section *** (СправСотр.ФИОСотр Get start)

                // *** End programmer edit section *** (СправСотр.ФИОСотр Get start)
                string result = this.fФИОСотр;
                // *** Start programmer edit section *** (СправСотр.ФИОСотр Get end)

                // *** End programmer edit section *** (СправСотр.ФИОСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправСотр.ФИОСотр Set start)

                // *** End programmer edit section *** (СправСотр.ФИОСотр Set start)
                this.fФИОСотр = value;
                // *** Start programmer edit section *** (СправСотр.ФИОСотр Set end)

                // *** End programmer edit section *** (СправСотр.ФИОСотр Set end)
            }
        }
        
        /// <summary>
        /// СправСотр.
        /// </summary>
        // *** Start programmer edit section *** (СправСотр.СправДолж CustomAttributes)

        // *** End programmer edit section *** (СправСотр.СправДолж CustomAttributes)
        [PropertyStorage(new string[] {
                "СправДолж"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_40.СправДолж СправДолж
        {
            get
            {
                // *** Start programmer edit section *** (СправСотр.СправДолж Get start)

                // *** End programmer edit section *** (СправСотр.СправДолж Get start)
                IIS.Prilozhenie_40.СправДолж result = this.fСправДолж;
                // *** Start programmer edit section *** (СправСотр.СправДолж Get end)

                // *** End programmer edit section *** (СправСотр.СправДолж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправСотр.СправДолж Set start)

                // *** End programmer edit section *** (СправСотр.СправДолж Set start)
                this.fСправДолж = value;
                // *** Start programmer edit section *** (СправСотр.СправДолж Set end)

                // *** End programmer edit section *** (СправСотр.СправДолж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправСотрE", typeof(IIS.Prilozhenie_40.СправСотр));
                }
            }
            
            /// <summary>
            /// "СправСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправСотрL", typeof(IIS.Prilozhenie_40.СправСотр));
                }
            }
        }
    }
}
