//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_40
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СправУчен.
    /// </summary>
    // *** Start programmer edit section *** (СправУчен CustomAttributes)

    // *** End programmer edit section *** (СправУчен CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправУченE", new string[] {
            "Фио as \'ФИО Ученика\'",
            "СправРод as \'Родитель\'",
            "СправРод.ФиоРод as \'Фио Родителя\'"})]
    [View("СправУченL", new string[] {
            "Фио as \'ФИО Ученика\'",
            "СправРод.ФиоРод as \'Фио Родителя\'"})]
    public class СправУчен : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        private IIS.Prilozhenie_40.СправРод fСправРод;
        
        // *** Start programmer edit section *** (СправУчен CustomMembers)

        // *** End programmer edit section *** (СправУчен CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (СправУчен.Фио CustomAttributes)

        // *** End programmer edit section *** (СправУчен.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (СправУчен.Фио Get start)

                // *** End programmer edit section *** (СправУчен.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (СправУчен.Фио Get end)

                // *** End programmer edit section *** (СправУчен.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправУчен.Фио Set start)

                // *** End programmer edit section *** (СправУчен.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (СправУчен.Фио Set end)

                // *** End programmer edit section *** (СправУчен.Фио Set end)
            }
        }
        
        /// <summary>
        /// СправУчен.
        /// </summary>
        // *** Start programmer edit section *** (СправУчен.СправРод CustomAttributes)

        // *** End programmer edit section *** (СправУчен.СправРод CustomAttributes)
        [PropertyStorage(new string[] {
                "СправРод"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_40.СправРод СправРод
        {
            get
            {
                // *** Start programmer edit section *** (СправУчен.СправРод Get start)

                // *** End programmer edit section *** (СправУчен.СправРод Get start)
                IIS.Prilozhenie_40.СправРод result = this.fСправРод;
                // *** Start programmer edit section *** (СправУчен.СправРод Get end)

                // *** End programmer edit section *** (СправУчен.СправРод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправУчен.СправРод Set start)

                // *** End programmer edit section *** (СправУчен.СправРод Set start)
                this.fСправРод = value;
                // *** Start programmer edit section *** (СправУчен.СправРод Set end)

                // *** End programmer edit section *** (СправУчен.СправРод Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправУченE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправУченE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправУченE", typeof(IIS.Prilozhenie_40.СправУчен));
                }
            }
            
            /// <summary>
            /// "СправУченL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправУченL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправУченL", typeof(IIS.Prilozhenie_40.СправУчен));
                }
            }
        }
    }
}
