//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_40
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СправРод.
    /// </summary>
    // *** Start programmer edit section *** (СправРод CustomAttributes)

    // *** End programmer edit section *** (СправРод CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправРодE", new string[] {
            "ФиоРод as \'Фио Родителя\'"})]
    [View("СправРодL", new string[] {
            "ФиоРод as \'Фио Родителя\'"})]
    public class СправРод : ICSSoft.STORMNET.DataObject
    {
        
        private string fФиоРод;
        
        // *** Start programmer edit section *** (СправРод CustomMembers)

        // *** End programmer edit section *** (СправРод CustomMembers)

        
        /// <summary>
        /// ФиоРод.
        /// </summary>
        // *** Start programmer edit section *** (СправРод.ФиоРод CustomAttributes)

        // *** End programmer edit section *** (СправРод.ФиоРод CustomAttributes)
        [StrLen(255)]
        public virtual string ФиоРод
        {
            get
            {
                // *** Start programmer edit section *** (СправРод.ФиоРод Get start)

                // *** End programmer edit section *** (СправРод.ФиоРод Get start)
                string result = this.fФиоРод;
                // *** Start programmer edit section *** (СправРод.ФиоРод Get end)

                // *** End programmer edit section *** (СправРод.ФиоРод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправРод.ФиоРод Set start)

                // *** End programmer edit section *** (СправРод.ФиоРод Set start)
                this.fФиоРод = value;
                // *** Start programmer edit section *** (СправРод.ФиоРод Set end)

                // *** End programmer edit section *** (СправРод.ФиоРод Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправРодE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправРодE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправРодE", typeof(IIS.Prilozhenie_40.СправРод));
                }
            }
            
            /// <summary>
            /// "СправРодL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправРодL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправРодL", typeof(IIS.Prilozhenie_40.СправРод));
                }
            }
        }
    }
}
